Update cassava_trait.obo
Planteome/CO_334-cassava-traits pull request #146
Opened 2022-09-06 14:23 UTC by marieALaporte

Description 
-----------------------------------------------------

Checklist 
---------------------------------------------------------------------------------------
- [ ] An OBO file generated from an OWL file
- [X] New terms
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [X] Term updates
  - [ ] The relevant issue has been closed.
  - [ ] Further work is required.
- [ ] CHECKS
  - [ ] New variables have a parent trait ID 
    - [ ] New variables have methods and scales 
  - [ ] The OBO file has been validated
    - [ ] checked in cassavabase
    - [ ] checked CropOntology

2022-09-06 14:24 UTC, marieALaporte commented
This fixed the issues regarding existing duplicated methods and added the remaining sensory traits for cassava for RTBFoods

2022-09-08 18:14 UTC, nmenda reviewed
"Attieke extraneous matters scale 0-1" appears twice - CO_334:0003060 and CO_334:0003061

2022-09-12 18:54 UTC, nmenda requested changes
please fix CO_334:0003060 and CO_334:0003061
Everything else looks good in Protege and Cassavabase:-)

2022-10-14 14:41 UTC, nmenda approved these changes

2022-10-14 14:41 UTC, merged